export const ROUTES = {
  AUTH: 'Auth',
  MAIN_TABS: 'MainTabs',
  HOME_TAB: 'HomeTab',
  MAIN_EVENT_TAB: 'MainEventTab',
  PROFILE_TAB: 'ProfileTab',
  NEWS_TAB: 'NewsTab',
  HOME_STACK: 'HomeStack',
  MAIN_EVENT_STACK: 'MainEventStack',
  PROFILE_STACK: 'ProfileStack',
  NEWS_STACK: 'NewsStack',
  MAIN_APP: 'MainApp',
  THE_PROBLEM: 'TheProblem',
  OUR_SOLUTION: 'OurSolution',
  WHY_CHOOSE_BMIC: 'WhyChooseBMIC',
  TOKENOMIC: 'Tokenomic',
  INVESTMENT_OPPORTUNITY: 'InvestmentOpportunity',
  ROADMAP: 'Roadmap',
  PROFILE: 'Profile',
  APP_INFO: 'AppInfo',
  ACCOUNT_SETTINGS: 'AccountSettings',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
  CALENDAR: 'Calendar',
  NEWS: 'News',
} as const;

export type RouteNames = typeof ROUTES[keyof typeof ROUTES];
